---
- name: Test Splunk Service
  hosts: splunk
  become: true
  tasks:
    - name: Check if Splunk is running
      command: /opt/splunk/bin/splunk status
      register: splunk_status
      failed_when: "'splunkd is running' not in splunk_status.stdout"

    - name: Display Success Message
      debug:
        msg: "Splunk version 10.0.2 is verified and running!"